version: "3.8"

services:
  app:
    build: .
    container_name: food-order-app
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mysql
    restart: always

  mysql:
    image: mysql:5.7
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: kapoor
      MYSQL_DATABASE: foodorderingwesitedb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data:
